### PR TITLE
Filesystem usage reduction

### PR DESCRIPTION
**Pull request by matteius**
Use the in memory HashCache and make DependencyCache not persist files.

### CODE REVIEW

**Comment by oz123** [comment]
Does removing the cache file, means that each run the dependency tree is re-created on the fly?
Is this going to make pipenv even slower?

**Review by oz123 — COMMENTED** [review]
I wonder about the effect this has on the speed of pipenv. Can you tell if there is a big difference?

**Comment by matteius** [comment]
@oz123  I believe this is an optimization,  keep in mind that the dependency tress is re-created on the fly every run of pipenv anyway because this was a NamedTemporaryFile that would get deleted at the end of the run and not some artifact that is persisted and reused between runs.   The the tests with the new requirementslib changes + the fix for skipping installing some packages ran at 0:09:17 this first run and 8:44 on subseqent run --  I then ran the tests on main and I think it maybe has an unfair advantage due to the bug where it skips installing packages already in site-packages, but for record that ran at `0:08:43`.   On the branch that perhaps fixes the site-packages issue, tests run came in at 0:08:45.  

Switched back to my test branch that includes this change one more time: 0:08:43.    It certainly doesn't have a negative impact on runtime, not exactly the performance boost I was hoping for but I think it simplifies things and eliminates some files usages that were not needed.

**Comment by oz123** [comment]
Thanks you for the clarification.

**Pull request merged**
