### PR TITLE
Fix Deprecation Warning when using setuptools >= v61.0.0

### LINKED ISSUE #315: `setuptools.config.read_configuration` is deprecated
Looks like `setuptools.config.read_configuration` was deprecated as of [setuptools `v61.0.0`](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6100). It also seems there are drop in replacements defined in `setuptools.config.setupcfg`.

https://github.com/sarugaku/requirementslib/blob/8de1e02318a3c4354ac6382f4461f8972145837e/src/requirementslib/models/setup_info.py#L515-L518

### PR DESCRIPTION
**Pull request by ytmimi**
- Fixes #315

### CODE REVIEW

**Review by matteius — APPROVED** [review]

**Comment by ytmimi** [comment]
@matteius thanks for reviewing the PR so quickly ❤️

**Comment by matteius** [comment]
Thanks for your contribution @ytmimi  -- not sure when to do a release next, but I'd like to see if anything in the new pipenv version that gets reported in the next couple weeks traces back to requirementslib or not in case there are more changes to make.

**Comment by ytmimi** [comment]
@matteius as I understand it `requirementslib` is vendored in pipenv. Would it be worth opening up a similar issue in the pipenv repo? Just want to know if there's anything else I can do to help here.

**Comment by matteius** [comment]
@ytmimi sure if you want to track it in pipenv open a ticket that is about -- release new version of requirementslib and vendor it in.  Thanks!

**Pull request merged**
