### PR TITLE
Fix an issue for projects with an at sign (`@`) in the path

### LINKED ISSUE #309: Support for paths with at sign (@)
It seems requirementslib is causing a crash in [pipenv](https://github.com/pypa/pipenv) in some rare circumstances.

### To reproduce:

- The user running the command has a home folder with an `@` sign in the name. In my example, the home folder is `/Users/some.user@acme.com`. 
  - While this may look weird and is probably not too common, it can be an issue with mobile user accounts on macOS. In some configurations, home folders may be set to the user's e-mail address when the user account is created, and this is actually valid.
  - I'm pretty sure you can reproduce the error by just putting the project inside a folder with an `@` sign anywhere in the path, but I haven't actually tried it myself.
- Create a python project within the path containing an `@` sign. In my example I use `/Users/some.user@acme.com/dev/myproject`.
- Define the project as an editable dependency in your `Pipfile`:
  ```
  [dev-packages]
  myproject = {editable = true, path = "."}
  ```
- Run `pipenv install --dev`.
- `pipenv` will crash with the following message (example):
  ```
  FileNotFoundError: [Errno 2] No such file or directory: '/Users/some.user'
  ```
  Full stack trace can be seen further down, but it is actually a red herring.

### The issue:
`pipenv` crashes [here](https://github.com/pypa/pipenv/blob/8753ceea30b2045d96fed112e70ca7e73d0ca08d/pipenv/environment.py#L769):
```python
if req.editable and req.line_instance.is_local and self.find_egg(match):
    requested_path = req.line_instance.path
    return requested_path and vistir.compat.samefile(requested_path, match.location)
```
The problem is that the property `req.line_instance.path` has stripped away everything after the `@` sign, containing just `/Users/some.user` in my example, while `match.location` contains the entire path.

The cause is the [`split_ref_from_uri(uri)` method](https://github.com/sarugaku/requirementslib/blob/330ad38e3ebe1fab99209aaa6373c5652b2b869e/src/requirementslib/models/utils.py#L555-L573) in this library. When [called from here](https://github.com/sarugaku/requirementslib/blob/330ad38e3ebe1fab99209aaa6373c5652b2b869e/src/requirementslib/models/requirements.py#L1165-L1166), you can probably see the issue:
```python
if path is not None and "@" in path:
    path, _ = split_ref_from_uri(path)
```
Here path will contain an `@` character, but it will not be an uri, meaning it is _not_ prefixed with `file://`. In the split method, scheme is thus set to `""`, and the following `if` check will be true:
```python
if scheme != "file" and "@" in path:
    path, _, ref = path.rpartition("@")
```
This strips away everything after the `@` character and thus `pipenv` crashes down the line.

### Full stack trace:
```$ pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (2fec9f)...

Traceback (most recent call last):
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/cli/command.py", line 194, in install
    do_install(
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/core.py", line 1996, in do_install
    do_init(
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/core.py", line 1260, in do_init
    do_install_dependencies(
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/core.py", line 823, in do_install_dependencies
    batch_install(
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/core.py", line 687, in batch_install
    deps_to_install = [
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/core.py", line 688, in <listcomp>
    dep for dep in deps_to_install if not project.environment.is_satisfied(dep)
  File "/Users/some.user@acme.com/dev/virtualenvs/myproject/lib/python3.9/site-packages/pipenv/environment.py", line 769, in is_satisfied
    return requested_path and vistir.compat.samefile(requested_path, match.location)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/some.user'
```

### PR DESCRIPTION
**Pull request by jervi**
It seems `requirementslib` is causing a crash in `pipenv` in some rare circumstances. If you define a package like this in a `Pipfile`:
```
myproject = {editable = true, path = "."}
```
and this project path contains an at sign (`@`), then requirementslib will parse the path wrong. The second clause in the added test case will fail without this fix.

Fixes #309

### CODE REVIEW

**Comment by matteius** [comment]
@jervi I have merged my changes into main -- if you can merge the latest main into your branch it should pass the next test run.

**Comment by jervi** [comment]
Thanks @matteius, I've rebased the branch now

**Comment by matteius** [comment]
@jervi it looks like the one failing test is for a VCS version which is a supported use case, so I think we have to sort out how to tell if the directory includes an @ or if the end of the path is specifying a vcs repository that is specifying the checkout version.

**Comment by jervi** [comment]
Hmm. I thought all the tests succeeded locally. I'll have another look.

**Comment by matteius** [comment]
@jervi I think that test does not run on Windows though.

**Comment by matteius** [comment]
@jervi let me know what your timeline is like; I'd like to do a release of this library in say a week or sooner if this gets finalized.   My rationale for a release soon is to get the new version of pip vendored into pipenv into a release for later in April.

**Comment by jervi** [comment]
Sorry, I meant to fix this during the last weekend, but things came up. I'll try to fix the test shortly - today or tomorrow 👍

**Comment by jervi** [comment]
Long days these days 😆 I'm really sorry for the long delay. It's a bit cumbersome that the tests don't run automatically, so I can't really confirm, but I think it's working now.

**Comment by jervi** [comment]
What is a valid git ref in this context? Is it only tags or sha's?  Or can it be branch names as well? This implementation will probably break if one are using a branch name for the ref and this branch contains a slash. I might need to adjust that regex a bit more...

**Comment by jervi** [comment]
Figured slashes in the ref names ought to be supported. This approach is maybe a bit naïve, but it's better than the previous attempt. All the existing tests works, and I added another test case that also works.

**Comment by nnutter** [comment]
I'm being hit by the bug this is trying to fix.  Is there anything blocking this from being merged?

**Comment by matteius** [comment]
@nnutter Just that I want more reviews and confidence that its not going to break something :-)  If you think it looks good, that helps me feel better about hitting the merge button.  I can try to get this into a release soon.

**Review by matteius — APPROVED** [review]

**Pull request merged**
