### PR TITLE
Full implementation of marker merging

### LINKED ISSUE #153: Merging markers always uses 'or' operator, but should 'and' on non-similar operators
Only markers with the same variable should be `or` combined, everything else should be `and` combined

### PR DESCRIPTION
**Pull request by techalchemy**
Full implementation of marker merging

- Allow `requirement.merge_markers(markers)` to traverse and merge
- Fixes #153

### CODE REVIEW

**Comment by pradyunsg** [comment]
Is the marker implementation merging logic mostly complete now?

**Comment by techalchemy** [comment]
@pradyunsg I haven't really written any tests for it yet, but probably not to be honest.  this is something of a hack but it sort of gets the job done

**Comment by pradyunsg** [comment]
Cool cool. No hurries.

I'm still not sure when I'd get my chunk of time work on this, so yea.

**Comment by techalchemy** [comment]
Hm I think this is pretty close to good, I have a lot of other stuff in here obviously since I'm trying to cut a pipenv release before I need to travel.

**Pull request merged**
